### ISSUE TITLE
Why levenshtein distance?

### ISSUE THREAD

**Issue by vaniakosmos** [davidadamojr/TextRank#15]
Textrank algorithm requires each node from graph to be connected with it neighbours in text. This makes it works with pagerank algo. But in your implementation you connect each node with every other node and weight edge with levenshtein distance (aka words textual similarity). 

In tests that I've made keywords from result wasn't actually keywords, but just random words that happens to be visually similar to the mean of other words in text (because of lev-dist).

Maybe I don't understand something? Can you explain usage of levenshtein distance? Or give some links where I can read about this. Tnx.

**Comment by davidadamojr** [comment]
There is no specific reason for using Levenshtein distance. This implementation was part of an **experiment** to assess the impact of different sentence similarity measures on the algorithm's performance. It is quite possible that Levenshtein distance is actually a horrible similarity measure to use in this context. Here is a quote from the original paper: 

> Other sentence similarity measures, such as string kernels, cosine similarity, longest common subsequence, etc. are also possible, and we are currently evaluating their impact on the summarization performance.

You can find the original TextRank paper here: https://web.eecs.umich.edu/~mihalcea/papers/mihalcea.emnlp04.pdf

**Comment by vaniakosmos** [comment]
Thank you for fast response 🙃
It's kinda strange, though, that no one asked about usage of levenshtein distance... I bet most of lib users just blindly accept keywords in result w/o checking that its are actually legit keywords (:
