### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by Devadath** [davidadamojr/TextRank#4]
Hi I would like to know how to run this code for only extracting keywords.
When I run the code, I get the error 
Traceback (most recent call last):
  File "textrank.py", line 25, in <module>
    @click.group()
Please help me.

**Comment by iwarriorgit** [comment]
don't simply run the code. You may `form textrand import extractKeyphrases`, and then `keywords_dict=extractKeyphrase(your_text)`

**Comment by iwarriorgit** [comment]
sorry, that's `form textrank import extractKeyphrases`, not `textrand`

**Comment by Devadath** [comment]
Thank you!. It worked!

Thanks & Regards
Devadath V V
