### ISSUE TITLE
problem with textrank.py

### ISSUE THREAD

**Issue by gopalshah1996** [davidadamojr/TextRank#6]
when i try to build the setup.py file , it is unable to find the textrank.py file..can u please help?
error:
running build
running build_py
file textrank.py (for module textrank) not found
file textrank.py (for module textrank) not found

**Comment by davidadamojr** [comment]
Have you tried doing "python setup.py install" instead?

**Comment by gopalshah1996** [comment]
yes sir , i have tried , while building it gives me that "textrank.py is not found". It would be really helpful if you could mail me stepwise procedure to run this library at email id:gopalshah1996@gmail.com. I am currently studying this research paper. Your esteemed help wil be much appreciated
